// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.30.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> privateKeyFromSeed({required List<int> seed, dynamic hint}) =>
    RustLib.instance.api.privateKeyFromSeed(seed: seed, hint: hint);

Future<String> toViewKey({required String privateKey, dynamic hint}) =>
    RustLib.instance.api.toViewKey(privateKey: privateKey, hint: hint);

Future<String> toAddress({required String privateKey, dynamic hint}) =>
    RustLib.instance.api.toAddress(privateKey: privateKey, hint: hint);

Future<String> transfer(
        {required String recipient,
        required String transferType,
        required double amount,
        required double fee,
        required bool privateFee,
        required String privateKey,
        String? amountRecord,
        String? feeRecord,
        String? endpoint,
        dynamic hint}) =>
    RustLib.instance.api.transfer(
        recipient: recipient,
        transferType: transferType,
        amount: amount,
        fee: fee,
        privateFee: privateFee,
        privateKey: privateKey,
        amountRecord: amountRecord,
        feeRecord: feeRecord,
        endpoint: endpoint,
        hint: hint);
